### PR TITLE
trying to template observer smartly

### PR DESCRIPTION
**Pull request by swom**
refer to issue #178

### CODE REVIEW

**Comment by swom** [comment]
@HHildenbrandt,
How should I do this the right way?
I feel like I shou;d template observer with just a simulation, but I need to deduce the type of the individuals in a simulation as well. I remember you saying something about this the last few minutes of the last programming session. 
Let me know if you have trouble finding this pull_request.

**Comment by HHildenbrandt** [comment]
Pass the template arguments as public typedefs:

template <mutation Mut>
class Network {
public:
  using mutation_type = Mut;
  ...
};

template <typename Net>
class Individual {
public:
  using network_type = Net;
  ...
};

template <typename Ind>
class Population {
public:
  using individual_type = Ind;
  ...
};

and so on...

template <typename Sim>
class Observer {
  using population_type = typename Sim::population_type;
  using individual_type = typename population_type::individual_type;
  ...
};

**Comment by swom** [comment]
Ok,
Thank you very much! 
One doubt I had about this solution is that type members are public. Could this lead to someone changing them by accident at run time?

**Comment by HHildenbrandt** [comment]
No, no chance ;)
Typedefs are just that - typedefs. They are pure compile-time things, they have no memory address and can't be changed at run-time. Look at std::vector. It defines a ton of public typedefs...

**Pull request merged**
