### PR TITLE
solved issue #131

### PR DESCRIPTION
**Pull request by Clemcarle**
#131

### CODE REVIEW

**Review by swom — COMMENTED** [review]
Bello 👌 
I will fix the merge conflicts

**Comment by swom** [comment]
As I suspected making them free functions messes up the template system a little bit, because now they take `network `as argument but they cannot take `mutator_network `nor a specific type of `mutator_network`. I need to think about this for a second. You can also try to fix this if you want. My solution would be to pass the pointer to a network, but I suspect this is not the best solution.

**Comment by swom** [comment]
Ah one more thing. As I noticed, you very correctly changed the `mutate_biases()` function to a free function. But then this is not called in `::mutate` member function of `mutator_network`, so we do not mutate biases. Add it in after all the `if/else constexpr`

**Comment by Clemcarle** [comment]
> Ah one more thing. As I noticed, you very correctly changed the `mutate_biases()` function to a free function. But then this is not called in `::mutate` member function of `mutator_network`, so we do not mutate biases. Add it in after all the `if/else constexpr`

Not quite, I made a `mutate_biases() `wrapper function; but it is still called in `mutate_weights`, which is called in `::mutate`. I might still move it to` ::mutate` so it also happens when we only mutate the activation, though.

**Comment by Clemcarle** [comment]
I'm not quite sure what kind of problem you ran into because I didn't have to do a,nything fancy to make things run. But anyway, here is a (I think) working solution.

**Pull request merged**
